# Generated by Django 6.0.1 on 2026-02-01 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ceeb_code', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.district')),
            ],
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('years_participated', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('in_leadership', models.BooleanField(default=False)),
                ('in_volunteering', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('gpa_scale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('class_size', models.IntegerField(blank=True, null=True)),
                ('num_advanced_courses', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('SAT', 'SAT'), ('ACT', 'ACT')], max_length=8)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('math_score', models.IntegerField(blank=True, null=True)),
                ('english_reading_score', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='core.student')),
            ],
        ),
    ]
