# Generated by Django 6.0.1 on 2026-02-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_college_ceeb_code_collegeapplication'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collegeapplication',
            index=models.Index(fields=['student', 'is_archived'], name='core_colleg_student_aca04f_idx'),
        ),
    ]
