# Generated by Django 6.0.1 on 2026-02-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collegeapplication_core_colleg_student_aca04f_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracurricularactivity',
            name='in_volunteering',
        ),
    ]
